### PR TITLE
Overhaul build system

### PR DESCRIPTION
**Pull request by fingolfin**
Switch to using Makefile.gappkg resp. gac to compile the kernel
extension. This drops the dependencies on libtool and automake.

### CODE REVIEW

**Comment by kamalsaleh** [comment]
Thank you Max. I have tried to install the package with this commit with gap-4.11 on ubuntu 18.04 and Arch Linux 4.19.93-1-lts; in both cases `autogen.sh && ./configure` results the following error:
`configure: error: cannot find install-sh, install.sh, or shtool in cnf "."/cnf`
Do have any ideas how to resolve this?

**Comment by fingolfin** [comment]
I have an idea, will update the PR later (have to look after the kid right now).
BTW I actually was hopi g that CI would verify this PR for me... But Travis is not running - I think an admin for this GitHub org (@mohamed-barakat?) needs to enable it. Alternatively we could try to set up GitHub Actions for this repo...

**Comment by mohamed-barakat** [comment]
I activated travis-ci.com for `CddInterface` and `NConvex`.

**Comment by kamalsaleh** [comment]
Thank you :)

**Pull request merged**
